### PR TITLE
Lint JSON files

### PR DESCRIPTION
**Pull request by txtsd**
@eepMoody Any input you might have would be great!
Once this is merged, it will be easier to parse descriptions to add additional attributes for #40 without breaking the formatting.

### CODE REVIEW

**Comment by eepMoody** [comment]
Hey @txtsd just did a quick merge with one of the preceeding MRs, but otherwise looks solid.

Could you include a lint config file and a note about what kind of linting you're using so future stuff can be consistent?

**Comment by txtsd** [comment]
At the moment, I run it through python's json module like this:

```python
import json

filenames = [
    '../open5e-api/data/creature_codex/document.json',
    '../open5e-api/data/creature_codex/monsters.json',
    '../open5e-api/data/open5e_original/backgrounds.json',
    '../open5e-api/data/open5e_original/document.json',
    '../open5e-api/data/open5e_original/spells.json',
    '../open5e-api/data/tome_of_beasts/document.json',
    '../open5e-api/data/tome_of_beasts/monsters.json',
    '../open5e-api/data/WOTC_5e_SRD_v5.1/backgrounds.json',
    '../open5e-api/data/WOTC_5e_SRD_v5.1/classes.json',
    '../open5e-api/data/WOTC_5e_SRD_v5.1/conditions.json',
    '../open5e-api/data/WOTC_5e_SRD_v5.1/document.json',
    '../open5e-api/data/WOTC_5e_SRD_v5.1/feats.json',
    '../open5e-api/data/WOTC_5e_SRD_v5.1/magicitems.json',
    '../open5e-api/data/WOTC_5e_SRD_v5.1/monsters.json',
    '../open5e-api/data/WOTC_5e_SRD_v5.1/planes.json',
    '../open5e-api/data/WOTC_5e_SRD_v5.1/races.json',
    '../open5e-api/data/WOTC_5e_SRD_v5.1/sections.json',
    '../open5e-api/data/WOTC_5e_SRD_v5.1/spells.json',
    '../open5e-api/data/WOTC_5e_SRD_v5.1/weapons.json',
    '../open5e-api/data/WOTC_5e_SRD_v5.1/armor.json',
]

for filename in filenames:
    with open(filename, 'r') as f:
        file = f.read()

    js = json.loads(file)

    with open(filename, 'w') as f:
        f.write(json.dumps(js, indent=4, ensure_ascii=False))
```

**Comment by txtsd** [comment]
@eepMoody Should I just push that as a file?

**Comment by txtsd** [comment]
With fixed paths, would this python file work, or are you looking for something different?

**Comment by txtsd** [comment]
Closing because of conflict. Redone in #66.

**Pull request closed without merging**
