### PR TITLE
Add Creature Codex stuff.

### PR DESCRIPTION
**Pull request by RealDeuce**
This is likely broken... and I'm just guessing at tables and line breaks.

### CODE REVIEW

**Comment by RealDeuce** [comment]
I suspect how I shoe-horned the OGL into the file is a part of why the check failed... but I can't actually see the details.

**Comment by eepMoody** [comment]
@RealDeuce it looks like the only issue was that your actions didn't include an "attack_bonus" except where it actually makes sense. The other files we used always included it, but it was simple enough to make the importer more flexible so we don't have to worry about it!

Assuming this passes, I think this PR is good to go.

**Comment by RealDeuce** [comment]
Did the table in the Elophar "Possessed by Ancestors" ability work?

**Comment by eepMoody** [comment]
@RealDeuce Took me a bit to find the right way to test this, but yeah the tables look good! Gonna merge this in.

**Pull request merged**
