### PR TITLE
Removing authentication controls and permissions. #36

### PR DESCRIPTION
**Pull request by augustjohnson**
Fixes issues #36

### CODE REVIEW

**Comment by augustjohnson** [comment]
Well that teaches me to do my dev on my local branch.  This ALSO includes some DEBUG work related to issue #34

**Comment by eepMoody** [comment]
@augustjohnson Sorry, I'm not really following what this does. Can you give a quick explanation just so I have something to refer back to if it ever comes up?

**Comment by augustjohnson** [comment]
On this page (https://api.open5e.com/) there's a Log in link in the upper right.  That link has no reason to exist.  The site offers no ability to auth, and all functions are available unauthenticated.  This PR is to remove the potential ability to log in at all (as it could be abused potentially).  

The benefit of this PR is a lower attack surface. There is no login form, anything posted to it will now be ignored, and all requests are now explicitly "Anonymous," with 0 authorization. There is no change in functionality other than an enhanced security posture.

**Comment by augustjohnson** [comment]
Ah, and the last benefit is that this actually will read the word "false" from .env and set the debug value to False, the python boolean value, not "false" the string (so it will no longer use debug mode).

**Comment by augustjohnson** [comment]
Thanks for the merge!  So I have identified that your .env in production does not include OPEN5E_DEBUG=False, so debug is still on in production...  I think this is a manual change somewhere.  it needs to be that exact string.

**Pull request merged**
